spring:
  application:
    name: authentication
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 300ms
  datasource:
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 30000
      filters: stat,wall,log4j
      time-between-eviction-runs-millis: 60000

server:
  port: 8001

management:
  endpoint:
    health:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
