spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: authentication
          uri: ${service.url.oauth}
          predicates:
            - Path=/oauth/**
  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 1000ms

server:
  port: 8866

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    refresh:
      enable: false

security:
  oauth2:
    client:
      client-id: gateway-client
      client-secret: elena-gateway-secret-1996
      user-authorization-uri: http://localhost:8001/oauth/token
    resource:
      id: gateway-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8001/oauth/check_token

service:
  url:
    oauth: http://localhost:8001
    plan: http://localhost:8002